name: Terraform + Image Build + AKS Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Prod

jobs:
# =========================
# STAGE 1: TERRAFORM
# =========================
  terraform:
    name: Terraform Deploy
    runs-on: self-hosted   # same as ADO self-hosted pool
    environment: ${{ inputs.environment }}

    env:
      ResourceGroup: RGP-USE-IACT1-DEV
      AKS: terraformmsaks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: |
            Infra/env.tfvars
            Infra/provider.tf
          tokenPrefix: "__"
          tokenSuffix: "__"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform init & workspace
        working-directory: Infra
        run: |
          key=$(az storage account keys list \
            --resource-group ${{ secrets.StorageAccountRG }} \
            --account-name ${{ secrets.StorageAccountName }} \
            --query "[0].value" -o tsv)

          echo "ARM_ACCESS_KEY=$key" >> $GITHUB_ENV

          terraform init -reconfigure
          terraform workspace new ${{ inputs.environment }} || true
          terraform workspace select ${{ inputs.environment }}

          echo "Applying for ${{ inputs.environment }} environment"

      - name: Terraform plan
        working-directory: Infra
        env:
          ARM_ACCESS_KEY: ${{ env.ARM_ACCESS_KEY }}
        run: terraform plan -var-file="env.tfvars" -lock=false

      - name: Terraform apply
        working-directory: Infra
        env:
          ARM_ACCESS_KEY: ${{ env.ARM_ACCESS_KEY }}
        run: terraform apply -var-file="env.tfvars" -auto-approve -lock=false


# =========================
# STAGE 2: IMAGE BUILD
# =========================
  image-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image to ACR
        run: |
          echo "Login to ACR"
          az acr login --name terraformmsacr

          echo "Building Docker Image"
          docker build -t terraformmsacr.azurecr.io/${{ vars.ImageName }}:latest ./app-1

          echo "Pushing image to ACR"
          docker push terraformmsacr.azurecr.io/${{ vars.ImageName }}:latest

          echo "Docker image pushed successfully"


# =========================
# STAGE 3: AKS DEPLOY
# =========================
  aks-deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: image-build
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy application to AKS
        run: |
          az account set --subscription "37a5f43b-7d53-4783-9782-c31e84937023"
          az account show

          echo "Getting AKS credentials"
          az aks get-credentials \
            --resource-group RGP-USE-IACT1-DEV \
            --name terraformmsaks \
            --overwrite-existing

          az aks update \
            -n terraformmsaks \
            -g RGP-USE-IACT1-DEV \
            --attach-acr terraformmsacr

          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

          kubectl describe svc my-app-service
          kubectl get deployments
          kubectl get pods

          echo "Deployment Completed"
