name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: Dev
        type: choice
        options:
          - Dev
          - Prod

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: self-hosted   # same as your ADO self-hosted pool

    env:
      ResourceGroup: RGP-USE-IACT1-DEV
      AKS: terraformmsaks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform (latest)
        uses: hashicorp/setup-terraform@v3

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: |
            Infra/env.tfvars
            Infra/provider.tf
          tokenPrefix: "__"
          tokenSuffix: "__"

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          client-id: ""
          tenant-id: ""
          subscription-id: ""
      

      - name: Terraform init & workspace
        working-directory: Infra
        run: |
          key=$(az storage account keys list \
            --resource-group ${{ secrets.StorageAccountRG }} \
            --account-name ${{ secrets.StorageAccountName }} \
            --query "[0].value" -o tsv)

          echo "ARM_ACCESS_KEY=$key" >> $GITHUB_ENV

          terraform init -reconfigure
          terraform workspace new ${{ inputs.environment }} || true
          terraform workspace select ${{ inputs.environment }}

          echo "Applying for ${{ inputs.environment }} Environment."

      - name: Terraform plan
        working-directory: Infra
        env:
          ARM_ACCESS_KEY: ${{ env.ARM_ACCESS_KEY }}
        run: |
          terraform plan -var-file="env.tfvars" -lock=false

      - name: Terraform apply
        working-directory: Infra
        env:
          ARM_ACCESS_KEY: ${{ env.ARM_ACCESS_KEY }}
        run: |
          terraform apply -var-file="env.tfvars" -auto-approve -lock=false
